### ISSUE TITLE
DAPS capability of holding one attribute

### ISSUE THREAD

**Issue by maximilianschmidt-zf** [Fraunhofer-AISEC/omejdn-server#64]
https://github.com/Fraunhofer-AISEC/omejdn-server/blob/c767a7a11e2776f1cbdb53f21ae74edd739ed138/omejdn.rb#L178-L190

We heard that the DAPS has the capability to contain only one claim, we would like to ask if 

`key, value = s.split(':', 2) `

is the reason for this capability. 

If yes it would be interesting why it is implemented in the way to hold only one attribute and not multiple ones?

**Comment by gbrost** [comment]
@bellebaum Would you like to answer? :)

**Comment by bellebaum** [comment]
This issue is related to the International Data Spaces Use case of Omejdn.

Hey and welcome to Omejdn :)
I am unsure what you mean by claim. The code you referenced deals with `scope`s, which are a concept in OAuth 2.
Within the IDS, the only defined scope to be requested from a DAPS is `idsc:IDS_CONNECTOR_ATTRIBUTES_ALL`, which is granted to all clients which have

1. `idsc:IDS_CONNECTOR_ATTRIBUTES_ALL` within their `scopes`, and
2. an attribute with key `idsc` and value including `IDS_CONNECTOR_ATTRIBUTES_ALL`, which is enforced by the referenced code.

I assume by claims you mean the actual claims present in the DAT. This works by looking up every granted scope in the scope mapping configuration section (`config/scope_mapping.yml` by default). Say it looks like this:

```yaml
idsc:IDS_CONNECTOR_ATTRIBUTES_ALL:
- key01
- key02
```

Then the attributes of the client with key `key01` and key `key02` are mapped to the client's userinfo, and (if the `token_user_attributes` plugin is loaded) to the access token (=DAT).

[The DAPS configuration repo](https://github.com/International-Data-Spaces-Association/omejdn-daps) demonstrates the necessary setup for a minimal IDS DAPS.

So you can basically map to the token whatever static claims you like, and if that does not suffice for your use case, you can extend the functionality quite easily by writing your own plugins :)

**Comment by maximilianschmidt-zf** [comment]
Thanks for the answer! 

So do I understand you correctly, we could add an infinite number of attributes in one token if we describe them in the scope_mapping.yaml ?

```
idsc:IDS_CONNECTOR_ATTRIBUTES_ALL:
- key01
- key02
- key03
- key04
- key05
- key06
- key07
- key08
```

**Comment by bellebaum** [comment]
Yes. Here is an example from the DAPS config repo:

```yaml
idsc:IDS_CONNECTOR_ATTRIBUTES_ALL:
- securityProfile
- referringConnector
- "@type"
- "@context"
- transportCertsSha256
```

So what gets mapped are the claims listed there, provided a client has attributes for them. You can of course add additional claims:

```yaml
idsc:IDS_CONNECTOR_ATTRIBUTES_ALL:
- securityProfile
- referringConnector
- "@type"
- "@context"
- transportCertsSha256
- myCustomClaim
```

**Comment by maximilianschmidt-zf** [comment]
Thanks, I got it! =)
