### ISSUE TITLE
Features and Specification

### ISSUE THREAD

**Issue by SebastianOpriel** [Fraunhofer-AISEC/omejdn-server#73]
With the last commit https://github.com/Fraunhofer-AISEC/omejdn-server/commit/31263245262c317b6ea3fea8262999d3f84463a8 a lot of things changed. I understand, that no new version was released, but could you nevertheless elaborate more on following points? 
- Are there breaking changes for service consumers (Connectors)?
- Which new features are to be expected with the commit and further developments? 
- What is planned with "Beginnings of Admin API v2" and what is the purpose?
- I heard that a DAPSv3 Spec is planned, which might adjust routes to `/.well-known/jwks.json`
- Is there some kind of roadmap for the next months what will be worked on?

**Comment by bellebaum** [comment]
Hey,

> - Are there breaking changes for service consumers (Connectors)?
> - I heard that a DAPSv3 Spec is planned, which might adjust routes to /.well-known/jwks.json

There shouldn't be. The OAuth 2.0 specification did not change, and Omejdn still aims to be compliant. That said, the JWKS URI mentioned is neither a real well-known URI, nor part of IDS-G.
It is a relic which is still needed for old connectors which still have this path hardcoded. The modern (and IDS-G compliant) way to discover this URI (and any other URIs related to the DAPS) is [documented in IDS-G](https://github.com/International-Data-Spaces-Association/IDS-G/blob/main/Components/IdentityProvider/DAPS/README.md#server-metadata).
Omejdn hasn't supported this URI for quite some time now and the [DAPS configuration repo](https://github.com/International-Data-Spaces-Association/omejdn-daps/blob/4704333cd9e0078101388f72af00f77e9ec7a94d/nginx.production.conf#L36) accounts for this via the reverse proxy.

> - What is planned with "Beginnings of Admin API v2" and what is the purpose?

Omejdn's Admin API v1 wasn't really stable, nor does it reflect Omejdn's capabilities.
It was simply meant as a way to read and write to the configuration files remotely, mainly from the UI.
But that meant that whenever the configuration file format changed, so did the API.
Of course, the usual way to deal with this is by modifying the API handler to hide the changes (or at least make them backwards-compatible), but this turned out to be challenging as well because the requests could not easily and reliably be translated. E.g. when the preliminary support for external OpenID-Providers got replaced with a more compliant Federation System, handled in a plugin.

Admin API v2 hopes to fix these issues, now that Omejdn has evolved quite a bit. It aims to provide a maintainable API based on well-defined, unlikely to change representations of the resources being available.
It is still unfinished, and work on it will probably be slow unless someone volunteers to contribute.
This does not mean that v1 will go away too soon, but it will be supported about as well as it is now.

> - Which new features are to be expected with the commit and further developments?
> - Is there some kind of roadmap for the next months what will be worked on?

Much of the work currently goes into making Omejdn more maintainable. This includes making upstream changes to the dependencies of Omejdn, like `ruby-jwt`, which I hope might eventually be able to handle all the certificate-related stuff which is not part of OAuth (which works with JOSE only apart from TLS).
A concrete roadmap does not exist at this point in time.

**Comment by SebastianOpriel** [comment]
Thanks for the detailed clarification! Looking forward to new releases.
